BOT_TOKEN = '7272107115:AAHcPL7zD_h4h_66C2ahOSgTqOYnHp0I7wc'
BOT_USERNAME = 'ZevoksBeeee_bot'
INVOICE_LINK = 't.me/send?start=IVMOkzcee53p'
CRYPTOBOT_TOKEN = '241216:AAxOMgnFkGTbm1zwcmnWQKkjHaYZCIvC4m7'
CHANNEL_ID = -1002149157913
LOGS_ID = -1002233739328
COEFFICIENT = 1.8
ADMINS = [7209512518]
NEWS_CHANNEL_LINK = 'https://t.me/+VW2kXhg4M2wxODE6'
CHAT_LINK = 'https://t.me/+401gADrB2Z5jMDAy'
SUPPORT_LINK = 'https://t.me/fgoopq'
ADAPTER_LINK = 'https://t.me/ZevoksBettCas'
HELP_LINK = 'https://t.me/c/2149157913/3'
LINKS_TEXT = '<b><a href="%s">Как сделать ставку?</a> | <a href="%s">Новостной канал</a> | <a href="%s">Наш чат</a> | <a href="%s">Техническая поддержка</a> | <a href="%s">Переходник</a></b>' % (HELP_LINK, NEWS_CHANNEL_LINK, CHAT_LINK, SUPPORT_LINK, ADAPTER_LINK)
WIN = 'https://i.yapx.cc/XXMkN.jpg'
LOSE = 'https://i.yapx.cc/XXMkP.jpg'
WHEEL_STICKERS = [
    'CAACAgIAAxkBAAJHY2ZK4EugC9Gq1_UZg5O7rc0zkECMAAIwRgACcR5YSsxeN2cqSN55NQQ',
    'CAACAgIAAxkBAAJHaGZK4IbY9cdpH9pQyVKKxBIgJp1mAAJrTAACiiBQSpLLXkHWXFmRNQQ',
    'CAACAgIAAxkBAAJHbWZK4JbtfAGB1c7S2CQhhStpyZp2AAKrUAACyDxZStpaiJq1vXwYNQQ',
    'CAACAgIAAxkBAAJHcmZK4KKmgY7VUKDlg8uB8XxInEpyAAJrTgAC6wlQSlFaIycWA8BLNQQ',
    'CAACAgIAAxkBAAJHd2ZK4K3WORtOT71TWNT4PJinhd0TAAIWSwACPrRQSjbb1N-xtzlCNQQ',
    'CAACAgIAAxkBAAJHfGZK4LWOvRbTaj9-2ZbW9ni8vVmBAALGTQAC8tpRSmX2N5zhZbCSNQQ',
    'CAACAgIAAxkBAAJHgWZK4L7Db6f9eRQgiejjLNUUzmL1AALLUAACOP9RSsIEL3ZdVul8NQQ',
    'CAACAgIAAxkBAAJHhmZK4MfJgOpySpYWpIZfB-6JUTnDAALSRQACUS5ZSgAB4PffQfZSjTUE',
    'CAACAgIAAxkBAAJHi2ZK4NBKl18c78Ru60_OCvlUM3TQAAKPTwACwEhQSjf2ZIzmrkH0NQQ',
    'CAACAgIAAxkBAAJHkGZK4Nk1-r84DFopq7ZaI_hA61FBAAKJQQACSElZSgca02gPfNOwNQQ',
    'CAACAgIAAxkBAAJHlWZK4OHHYBdeKlneCAvtwntZVu4WAALlUQACSslRSqAz04vd8IHZNQQ',
    'CAACAgIAAxkBAAJHmmZK4PxUwpceRrtb8IEcqfA56tyjAAKAQAACSeVYSrwY_-Y8UybdNQQ',
    'CAACAgIAAxkBAAJHn2ZK4Q9I57vLSYA-anKKuJZE9uXKAALyQAACI9JZSoNAsgkJzDixNQQ',
    'CAACAgIAAxkBAAJHpGZK4RkuaYSXGRYW72H0wf02pu-GAAIsRwACWttZSiLVhjoQ4Wr3NQQ',
    'CAACAgIAAxkBAAJHqWZK4SPaJ0Fag7JUmYRBn8h14phjAALDUQAC_R5YSqbWZqb4v7klNQQ',
    'CAACAgIAAxkBAAJHrmZK4S3oAx1qvTPeW1QaCGHmkiP2AAKFPwACZoVYSoSlEySyxPKHNQQ',
    'CAACAgIAAxkBAAJHuGZK4UHeW0BiVPugWkzLAAGMDBV6yAACoEcAAl5EWUqVzM66FWlaaDUE',
    'CAACAgIAAxkBAAJHvWZK4U9G5Lx9VRgED8cMcJMAAUbT-wACeUUAAkyFWEoBVKx02Trj-DUE',
    'CAACAgIAAxkBAAJHwmZK4VgKxtXlfN7HwkTTsGyntNFJAAKCTAAC1HhZSpIPt_i6azLDNQQ',
    'CAACAgIAAxkBAAJHx2ZK4WeN3VmJKOURQtJTInu5ngngAAJITwACg-1RSqIyu4NVRnVINQQ',
    'CAACAgIAAxkBAAJHzGZK4XEwXB_znllBgIshEFEZRaIxAAISRQACFL1YSrvOt1GakqjVNQQ',
    'CAACAgIAAxkBAAJH0WZK4Z6P4H3t1uwUnF6_KQlCME8jAAK9TAAD4VFKWFKFavkoptc1BA',
    'CAACAgIAAxkBAAJH1mZK4a7skyxTOgGjFWI4-_5SjOCeAAK9VQACZEhZSl1pOu5igiJHNQQ',
    'CAACAgIAAxkBAAJH22ZK4bYRAlYKQ7oxNisDPJ_C-cnjAALPRQACNXhYSv_URcZUfbGhNQQ',
    'CAACAgIAAxkBAAJH4GZK4cG2s42OnRty070byHsftAhyAAJUTwACQUNQSs_FMkbailSkNQQ',
    'CAACAgIAAxkBAAJH5WZK4ctD4VPeAk7EuYGmRDN51iQxAALrTQAChuZYSig2ESLH9rqYNQQ',
    'CAACAgIAAxkBAAJH6mZK4dVA-9noUy_5QQJT7LqHPqc9AAKJTAACPzdYSjFvOqZ07_YHNQQ',
    'CAACAgIAAxkBAAJH72ZK4d-N1uhzUMHNrXIiQm7FYjosAALTQAAC7B5YSluN6htKrN-0NQQ',
    'CAACAgIAAxkBAAJH9GZK4ejBVUIL81XlOWs9vYV7H7vHAAJTQgACP2dYSuau52wSi5i7NQQ',
    'CAACAgIAAxkBAAJH-WZK4fAlVyhGsvoChkevtltQ3RdqAAKsYwACq5dZSnTQK_jn5ZnONQQ',
    'CAACAgIAAxkBAAJH_mZK4fiRl47v8pvPZNWVysxhF3XcAALoQQACJ39ZSnuJXNphXz8DNQQ',
    'CAACAgIAAxkBAAJIA2ZK4gRGIhEpklIW6SwNKROgAqWJAALhUgACgS1YSvT6_975eTjzNQQ',
    'CAACAgIAAxkBAAJIDWZK4hPRrQSdITsE89UePfc4_10aAALxUwACPONYSgmmdH8ana9HNQQ',
    'CAACAgIAAxkBAAJICGZK4gxyuGUbuhU5RMsvwIrQS4AEAALZRAAC-aVZSqMh89Rth0AzNQQ',
    'CAACAgIAAxkBAAJIEmZK4ivYukC_4eMVqCUPThmwaXJmAAL5RgAC6VZYSmEGB6tsZg4hNQQ',
    'CAACAgIAAxkBAAJIF2ZK4ji_iEQmIeLqFRkopTybXzJcAAK0TwACYzBRShhbPLw--dklNQQ',
    'CAACAgIAAxkBAAJIHGZK4kXjYonasGG3QpU7LeUD35XzAAKlSwACnSlZSsgAATI_BnO_OTUE'
]
HEADS_AND_TAILS_STICKERS = [
    'CAACAgIAAxUAAWZZlWAxityDairlJDjt0TtVJn6UAALaTgACFjLJSg2YsLjSsD1KNQQ',
    'CAACAgIAAxkBAAJMDWZZlWLYh-kChFTZAAEl8rM--_QjvAAC2EMAAisi0UrwCHRI3c-BlzUE'
]
